spring.application.name=library

# Configuration de la base de données MariaDB
spring.datasource.url=${DB_URL:jdbc:mariadb://localhost:3306/library_db}
spring.datasource.username=${DB_USERNAME:library}
spring.datasource.password=${DB_PASSWORD:library}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuration de Hibernate : met à jour le schéma de la base de données automatiquement
spring.jpa.hibernate.ddl-auto=update
